version: 2.1
# Using 2.1 will give access to new features 
orbs: 
  sonarqube: psl/sonarscanner@0.0.4 # using sonarscanner orb 
  
jobs:
  sonarscanner:
    docker:
      - image: cimg/python:3.10.6
      # using cimg 
      # use can use any relevant image
    working_directory: ~/workspace/circleci
      # set a working directory for the job       
    steps:
     - checkout
     - run: 
        name: Install Sonarqube sonarscanner
        # install sonarscanner on your machine
        command: |
          export SONAR_SCANNER_VERSION=4.7.0.2747
          export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
          curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip          
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          export PATH=$SONAR_SCANNER_HOME/bin:$PATH
          export SONAR_SCANNER_OPTS="-server"
          sonar-scanner -v
          # get the version of the sonar scanner 
          which sonar-scanner  
     - run: 
          pip install -U pytest pytest-cov
    #  - run:
#           pip install coverage
# #           python -m coverage --version
     - run:
          python -m unittest -v test_calc.py
#         coverage run test_calc.py test_employee.py 
#         coverage report
#         coverage xml
#         python -m pytest --cov-branch=main --cov=python-mini-projects --cov-config=.coveragerc --cov-report=xml --cov=src .
     - run:          
          pwd
          ls -a
         
     - store_test_results:
          name: store results to coverage.xml
          path: ~/workspace/circleci/
     - run:          
          pwd
          ls -a

     - run:
        name: Execute Sonarqube sonarscanner
        command: |
          /home/circleci/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner \
          -Dsonar.projectKey=python-mini-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://52.208.63.176:9000  \
          -Dsonar.python.coverage.reportPath=coverage.xml
workflows:
  version: 2
  sonarqube:
    jobs:
      - sonarscanner
#       - python/test:
#           args: '--dev'
#           pkg-manager: pipenv
#           test-tool: pytest
