version: 2.1  
orbs:                                                                      
    sonarcloud: sonarsource/sonarcloud@1.1.1
jobs:
    buildanddeploy:
        docker :
            - image: cimg/deploy:2022.07
        working_directory: ~/workspace/circleci
        steps:
            - checkout 
            - sonarcloud/scan
workflows: 
    version: 2 
    build:
        jobs:  
            - buildanddeploy:
                context: SonarCloud
